"""The slice of OllamaClient that preflight and calibration need; lets tests inject a fake."""

from __future__ import annotations

from typing import Protocol

from harness.guard.ollama_client import ModelInfo, ModelTag, RunningModel


class Backend(Protocol):
    def pin(self, model: str, num_ctx: int) -> None: ...
    async def version(self) -> str: ...
    async def tags(self) -> list[ModelTag]: ...
    async def show(self, model: str) -> ModelInfo: ...
    async def ps(self) -> list[RunningModel]: ...
    async def warm(self, model: str) -> None: ...
    async def unload(self, model: str) -> None: ...
